[[headers]]
    for = "*.mp4"
    [headers.values]
        cache-control = "public, max-age=31536000"
[[headers]]
    for = "*.jpg"
    [headers.values]
        cache-control = "public, max-age=31536000"
